[package]
name = "infra"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
discern = { workspace = true }
sea-orm = { workspace = true }
tracing = { workspace = true }
